# EDA MAIN

In [106]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

pd.pandas.set_option('display.max_columns', None)

print(pd.__version__)
print(np.__version__)
print(sklearn.__version__)
print(tf.__version__)

2.2.2
1.26.4
1.5.0
2.16.2

In [177]:
import pandas as pd
df = pd.read_csv('Crop_Yield_Prediction.csv')
op = df['Yield']
df.drop(columns=['Yield'], inplace=True)

In [178]:
print(df.head())

   Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
0        90          42         43    20.879744  82.002744  6.502985
1        85          58         41    21.770462  80.319644  7.038096
2        60          55         44    23.004459  82.320763  7.840207
3        74          35         40    26.491096  80.158363  6.980401
4        78          42         42    20.130175  81.604873  7.628473

     Rainfall  Crop
0  202.935536  Rice
1  226.655537  Rice
2  263.964248  Rice
3  242.864034  Rice
4  262.717340  Rice

In [179]:
# One-hot encode categorical features
df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded = df_encoded.astype(int)

print(df_encoded.head())

# label_encoder = LabelEncoder()

# # Apply LabelEncoder to each feature in the list
# df['Crop'] = label_encoder.fit_transform(df['Crop'])
# df_encoded = df
# print(df_encoded.head())
# correlation_matrix = df_encoded.corr()
# plt.figure(figsize=(50, 40))
# sns.heatmap(correlation_matrix, cmap='BrBG', annot=True, fmt=".2f", linewidths=.5)
# plt.show()

   Nitrogen  Phosphorus  Potassium  Temperature  Humidity  pH_Value  Rainfall  \
0        90          42         43           20        82         6       202
1        85          58         41           21        80         7       226
2        60          55         44           23        82         7       263
3        74          35         40           26        80         6       242
4        78          42         42           20        81         7       262

   Crop_Banana  Crop_Blackgram  Crop_ChickPea  Crop_Coconut  Crop_Coffee  \
0            0               0              0             0            0
1            0               0              0             0            0
2            0               0              0             0            0
3            0               0              0             0            0
4            0               0              0             0            0

   Crop_Cotton  Crop_Grapes  Crop_Jute  Crop_KidneyBeans  Crop_Lentil  \
0            0            0          0                 0            0
1            0            0          0                 0            0
2            0            0          0                 0            0
3            0            0          0                 0            0
4            0            0          0                 0            0

   Crop_Maize  Crop_Mango  Crop_MothBeans  Crop_MungBean  Crop_Muskmelon  \
0           0           0               0              0               0
1           0           0               0              0               0
2           0           0               0              0               0
3           0           0               0              0               0
4           0           0               0              0               0

   Crop_Orange  Crop_Papaya  Crop_PigeonPeas  Crop_Pomegranate  Crop_Rice  \
0            0            0                0                 0          1
1            0            0                0                 0          1
2            0            0                0                 0          1
3            0            0                0                 0          1
4            0            0                0                 0          1

   Crop_Watermelon
0                0
1                0
2                0
3                0
4                0

In [180]:
# df_encoded['Yield'] = op
df_encoded.head()

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall,Crop_Banana,Crop_Blackgram,Crop_ChickPea,Crop_Coconut,Crop_Coffee,Crop_Cotton,Crop_Grapes,Crop_Jute,Crop_KidneyBeans,Crop_Lentil,Crop_Maize,Crop_Mango,Crop_MothBeans,Crop_MungBean,Crop_Muskmelon,Crop_Orange,Crop_Papaya,Crop_PigeonPeas,Crop_Pomegranate,Crop_Rice,Crop_Watermelon
0,90,42,43,20,82,6,202,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,85,58,41,21,80,7,226,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,60,55,44,23,82,7,263,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,74,35,40,26,80,6,242,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,78,42,42,20,81,7,262,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [181]:
nan_dfc = [feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtype=='O']
for f in nan_dfc:
    print("{} : {}% nans {}".format(f, np.round(df[f].isnull().mean(), 4), df[f].dtype))

In [182]:
nan_dfn = [feature for feature in df.columns if df[feature].isnull().sum()>1 and df[feature].dtype!='O']
for f in nan_dfn:
    print("{} : {}% nans {}".format(f, np.round(df[f].isnull().mean(), 4), df[f].dtype))

In [183]:
nmf = [feature for feature in df.columns if df[feature].dtype!='O']
print(nmf)

['Nitrogen', 'Phosphorus', 'Potassium', 'Temperature', 'Humidity', 'pH_Value', 'Rainfall']

In [184]:
df.count()

Nitrogen       2200
Phosphorus     2200
Potassium      2200
Temperature    2200
Humidity       2200
pH_Value       2200
Rainfall       2200
Crop           2200
dtype: int64

In [191]:
scrl = StandardScaler()
df_scaled = scrl.fit_transform(df_encoded)  # Scale the features

# Split data
x_train, x_test, y_train, y_test = train_test_split(df_scaled, op, test_size=0.2, random_state=42)

# Create and train the model
model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test, y_test)

-0.16561509559899656

# Crop recomnd

In [194]:
df = pd.read_csv('Crop_recommendation.csv')

op = df.label
df.drop(columns=['label'], inplace=True)
df.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [195]:
label_encoder = LabelEncoder()

# Apply LabelEncoder to each feature in the list
y = label_encoder.fit_transform(op)

# Verify the encoding
print(y)

[20 20 20 ...  5  5  5]

In [196]:
x = df
model = RandomForestClassifier()
model.fit(x, y)

# New data for prediction
new_data = [[75, 45, 40, 25, 80.5, 7, 250]]
new_data_df = pd.DataFrame(new_data, columns=x.columns)  # Use same columns as training data

# Make predictions
predictions = model.predict(new_data_df)

# Assuming label_encoder is already fitted
decoded_predictions = label_encoder.inverse_transform(predictions)

print(decoded_predictions)

['rice']

# Rainfall

In [221]:
df1 = pd.read_csv('district wise rainfall normal.csv')

In [222]:
df1.columns

Index(['STATE_UT_NAME', 'DISTRICT', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
       'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb',
       'Mar-May', 'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [227]:
unique_states = df1['DISTRICT'].unique()
print(unique_states)
# Convert the unique values to a comma-separated string
unique_states_str = ', '.join(map(str, unique_states))
print("Unique States/UTs:", unique_states_str)

['NICOBAR' 'SOUTH ANDAMAN' 'N & M ANDAMAN' 'LOHIT' 'EAST SIANG'
 'SUBANSIRI F.D' 'TIRAP' 'ANJAW (LOHIT)' 'LOWER DIBANG' 'CHANGLANG'
 'PAPUM PARE' 'LOW SUBANSIRI' 'UPPER SIANG' 'WEST SIANG' 'DIBANG VALLEY'
 'WEST KAMENG' 'EAST KAMENG' 'TAWANG(W KAME' 'KURUNG KUMEY' 'CACHAR'
 'DARRANG' 'GOALPARA' 'KAMRUP' 'LAKHIMPUR' 'NORTH CACHAR' 'NAGAON'
 'SIVASAGAR' 'BARPETA' 'DHUBRI' 'DIBRUGARH' 'JORHAT' 'KARIMGANJ'
 'KOKRAJHAR' 'SHONITPUR' 'GOLAGHAT' 'TINSUKIA' 'HAILAKANDI'
 'DHEMAJI(LAKHI' 'KARBI ANGLONG' 'UDALGURI(DARA' 'KAMRUP METROP'
 'CHIRANG(BONGAI' 'BAKSA BARPETA' 'BONGAIGAON' 'MORIGAON' 'NALBARI'
 'EAST KHASI HI' 'JAINTIA HILLS' 'EAST GARO HIL' 'RI-BHOI' 'SOUTH GARO HI'
 'W KHASI HILL' 'WEST GARO HIL' 'IMPHAL EAST' 'SENAPATI' 'TAMENGLONG'
 'CHANDEL' 'UKHRUL' 'THOUBAL' 'BISHNUPUR' 'IMPHAL WEST' 'CHURACHANDPUR'
 'AIZAWL' 'CHAMPHAI' 'KOLASIB' 'LUNGLEI' 'CHHIMTUIPUI' 'LAWNGTLAI' 'MAMIT'
 'SAIHA' 'SERCHHIP' 'KOHIMA' 'TUENSANG' 'MOKOKCHUNG' 'DIMAPUR' 'WOKHA'
 'MON' 'ZUNHEBOTO' 'PHEK' 'KEPHRIE' 'LONGLENG' 'PEREN' 'NORTH TRIPURA'
 'SOUTH TRIPURA' 'WEST TRIPURA' 'DHALAI' 'COOCH BEHAR' 'DARJEELING'
 'JALPAIGURI' 'MALDA' 'SOUTH DINAJPUR' 'NORTH DINAJPUR' 'NORTH SIKKIM'
 'EAST SIKKIM' 'WEST SIKKIM' 'SOUTH SIKKIM' 'BANKURA' 'BIRBHUM' 'BURDWAN'
 'HOOGHLY' 'HOWRAH' 'PURULIA' 'MURSHIDABAD' 'NADIA' 'NORTH 24 PARG'
 'SOUTH 24 PARG' 'EAST MIDNAPOR' 'WEST MIDNAPOR' 'KOLKATA' 'BALASORE'
 'BOLANGIR' 'KANDHAMAL/PHU' 'CUTTACK' 'DHENKANAL' 'GANJAM' 'KALAHANDI'
 'KEONDJHARGARH' 'KORAPUT' 'MAYURBHANJ' 'PURI' 'SAMBALPUR' 'SUNDARGARH'
 'BHADRAK' 'JAJPUR' 'KENDRAPARA' 'ANGUL' 'NAWAPARA' 'MALKANGIRI'
 'NAWARANGPUR' 'NAYAGARH' 'KHURDA' 'BARGARH' 'JHARSUGUDA' 'DEOGARH'
 'RAYAGADA' 'GAJAPATI' 'JAGATSINGHAPU' 'BOUDHGARH' 'SONEPUR' 'BOKARO'
 'DHANBAD' 'DUMKA' 'HAZARIBAG' 'PALAMU' 'RANCHI' 'SAHIBGANJ'
 'WEST SINGHBHUM' 'DEOGHAR' 'GIRIDIH' 'GODDA' 'GUMLA' 'LOHARDAGA' 'CHATRA'
 'KODERMA' 'PAKUR' 'EAST SINGHBHU' 'GARHWA' 'SERAIKELA-KHA' 'JAMTARA'
 'LATEHAR' 'SIMDEGA' 'KHUNTI(RANCHI' 'RAMGARH' 'BHAGALPUR'
 'EAST CHAMPARAN' 'DARBHANGA' 'GAYA' 'MUNGER' 'MUZAFFARPUR'
 'WEST CHAMPARAN' 'PURNEA' 'GOPALGANJ' 'MADHUBANI' 'AURANGABAD'
 'BEGUSARAI' 'BHOJPUR' 'NALANDA' 'PATNA' 'KATIHAR' 'KHAGARIA' 'SARAN'
 'MADHEPURA' 'NAWADA' 'ROHTAS' 'SAMASTIPUR' 'SITAMARHI' 'SIWAN' 'VAISHALI'
 'JAHANABAD' 'BUXAR' 'ARARIA' 'BANKA' 'BHABUA' 'JAMUI' 'KISHANGANJ'
 'SHEIKHPURA' 'SUPAUL' 'LAKHISARAI' 'SHEOHAR' 'ARWAL' 'SAHARSA'
 'ALLAHABAD' 'AZAMGARH' 'BAHRAICH' 'BALLIA' 'BANDA' 'BARABANKI' 'BASTI'
 'DEORIA' 'FAIZABAD' 'FARRUKHABAD' 'FATEHPUR' 'GHAZIPUR' 'GONDA'
 'GORAKHPUR' 'HARDOI' 'JAUNPUR' 'KANPUR NAGAR' 'KHERI LAKHIMP' 'LUCKNOW'
 'MIRZAPUR' 'PRATAPGARH' 'RAE BARELI' 'SITAPUR' 'SULTANPUR' 'UNNAO'
 'VARANASI' 'SONBHADRA' 'MAHARAJGANJ' 'MAU' 'SIDDHARTH NGR' 'KUSHINAGAR'
 'AMBEDKAR NAGAR' 'KANNAUJ' 'BALRAMPUR' 'KAUSHAMBI' 'SAHUJI MAHARA'
 'KANPUR DEHAT' 'CHANDAULI' 'SANT KABIR NGR' 'SANT RAVIDAS'
 'SHRAVASTI NGR' 'AGRA' 'ALIGARH' 'BAREILLY' 'BIJNOR' 'BADAUN'
 'BULANDSHAHAR' 'ETAH' 'ETAWAH' 'HAMIRPUR' 'JALAUN' 'JHANSI' 'LALITPUR'
 'MAINPURI' 'MATHURA' 'MEERUT' 'MORADABAD' 'MUZAFFARNAGAR' 'PILIBHIT'
 'RAMPUR' 'SAHARANPUR' 'SHAHJAHANPUR' 'GHAZIABAD' 'FIROZABAD' 'MAHOBA'
 'MAHAMAYA NAGA' 'AURAIYA' 'BAGPAT' 'JYOTIBA PHULE' 'GAUTAM BUDDHA'
 'KANSHIRAM NAG' 'ALMORA' 'CHAMOLI' 'DEHRADUN' 'GARHWAL PAURI' 'NAINITAL'
 'PITHORAGARH' 'GARHWAL TEHRI' 'UTTARKASHI' 'HARIDWAR' 'CHAMPAWAT'
 'RUDRAPRAYAG' 'UDHAM SINGH N' 'BAGESHWAR' 'AMBALA' 'GURGAON' 'HISAR'
 'JIND' 'KARNAL' 'MAHENDRAGARH' 'ROHTAK' 'BHIWANI' 'FARIDABAD'
 'KURUKSHETRA' 'SIRSA' 'SONEPAT(RTK)' 'YAMUNANAGAR' 'KAITHAL' 'PANIPAT'
 'REWARI' 'FATEHABAD' 'JHAJJAR' 'PANCHKULA' 'MEWAT' 'PALWAL(FRD)'
 'CHANDIGARH' 'NEW DELHI' 'CENTRAL DELHI' 'EAST DELHI' 'NORTH DELHI'
 'NE DELHI' 'SW DELHI' 'NW DELHI' 'SOUTH DELHI' 'WEST DELHI' 'AMRITSAR'
 'BATHINDA' 'FEROZEPUR' 'GURDASPUR' 'HOSHIARPUR' 'JALANDHAR' 'KAPURTHALA'
 'LUDHIANA' 'PATIALA' 'RUPNAGAR' 'SANGRUR' 'FARIDKOT' 'MOGA' 'NAWANSHAHR'
 'FATEHGARH SAH' 'MUKTSAR' 'MANSA' 'BARNALA' 'SAS NAGAR(MGA)' 'TARN TARAN'
 'BILASPUR' 'CHAMBA' 'KANGRA' 'KINNAUR' 'KULLU' 'LAHUL & SPITI' 'MANDI'
 'SHIMLA' 'SIRMAUR' 'SOLAN' 'UNA' 'ANANTNAG' 'BARAMULLA' 'DODA' 'JAMMU'
 'KATHUA' 'LADAKH (LEH)' 'UDHAMPUR' 'BADGAM' 'KUPWARA' 'PULWAMA'
 'SRINAGAR' 'KARGIL' 'POONCH' 'RAJOURI' 'BANDIPORE' 'GANDERWAL'
 'KULGAM/(ANT)' 'SHOPAN' 'SAMBA' 'KISTWAR' 'REASI' 'RAMBAN(DDA)' 'BARMER'
 'BIKANER' 'CHURU' 'SRI GANGANAGA' 'JAISALMER' 'JALORE' 'JODHPUR' 'NAGAUR'
 'PALI' 'HANUMANGARH' 'AJMER' 'ALWAR' 'BANSWARA' 'BHARATPUR' 'BHILWARA'
 'BUNDI' 'CHITTORGARH' 'DUNGARPUR' 'JAIPUR' 'JHALAWAR' 'JHUNJHUNU' 'KOTA'
 'SAWAI MADHOPUR' 'SIKAR' 'SIROHI' 'TONK' 'UDAIPUR' 'DHOLPUR' 'BARAN'
 'DAUSA' 'RAJSAMAND' 'KARAULI' 'PRATAPGARH(CHT' 'BETUL' 'VIDISHA' 'BHIND'
 'DATIA' 'DEWAS' 'DHAR' 'GUNA' 'GWALIOR' 'HOSHANGABAD' 'INDORE' 'JHABUA'
 'MANDSAUR' 'MORENA' 'KHANDWA' 'KHARGONE' 'RAISEN' 'RAJGARH' 'RATLAM'
 'SEHORE' 'SHAJAPUR' 'SHIVPURI' 'UJJAIN' 'BHOPAL' 'HARDA' 'NEEMUCH'
 'SHEOPUR' 'BARWANI' 'ASHOKNAGAR(GNA' 'BURHANPUR' 'ALIRAJPUR(JBA)'
 'BALAGHAT' 'CHHATARPUR' 'CHHINDWARA' 'JABALPUR' 'MANDLA' 'NARSINGHPUR'
 'PANNA' 'REWA' 'SAGAR' 'SATNA' 'SEONI' 'SHAHDOL' 'SIDHI' 'TIKAMGARH'
 'KATNI' 'DINDORI' 'UMARIA' 'DAMOH' 'ANUPPUR(SHAHD' 'SINGRAULI'
 'AHMEDABAD' 'BANASKANTHA' 'BARODA' 'BHARUCH' 'VALSAD' 'DANGS' 'KHEDA'
 'MEHSANA' 'PANCHMAHALS' 'SABARKANTHA' 'SURAT' 'GANDHINAGAR'
 'NARMADA(BRC)' 'NAVSARI(VSD)' 'ANAND(KHR)' 'PATAN(MHSN)' 'DAHOD(PNML)'
 'TAPI(SRT)' 'AMRELI' 'BHAVNAGAR' 'JAMNAGAR' 'JUNAGADH' 'KUTCH' 'RAJKOT'
 'SURENDRANAGAR' 'PORBANDAR' 'DNH' 'DAMAN' 'DIU' 'MUMBAI CITY' 'RAIGAD'
 'RATNAGIRI' 'THANE' 'SINDHUDURG' 'MUMBAI SUB' 'NORTH GOA' 'SOUTH GOA'
 'AHMEDNAGAR' 'DHULE' 'JALGAON' 'KOLHAPUR' 'NASHIK' 'PUNE' 'SANGLI'
 'SATARA' 'SOLAPUR' 'NANDURBAR' 'BEED' 'NANDED' 'OSMANABAD' 'PARBHANI'
 'LATUR' 'JALNA' 'HINGOLI' 'AKOLA' 'AMRAVATI' 'BHANDARA' 'BULDHANA'
 'CHANDRAPUR' 'NAGPUR' 'YAVATMAL' 'WARDHA' 'GADCHIROLI' 'WASHIM' 'GONDIA'
 'BASTAR' 'DURG' 'RAIGARH' 'RAIPUR' 'SURGUJA' 'RAJNANDGAON' 'DANTEWADA'
 'KANKER (NORH' 'JANJGIR-CHAMP' 'KORBA' 'JASHPUR' 'DHAMTARI' 'MAHASAMUND'
 'KORIYA' 'KOWARDHA (KAB' 'NARAYANPUR' 'BIJAPUR' 'EAST GODAVARI'
 'WEST GODAVARI' 'GUNTUR' 'KRISHNA' 'NELLORE' 'PRAKASAM' 'SRIKAKULAM'
 'VISAKHAPATNAM' 'VIZIANAGARAM' 'ADILABAD' 'HYDERABAD' 'KARIMNAGAR'
 'KHAMMAM' 'MAHABUBNAGAR' 'MEDAK' 'NALGONDA' 'NIZAMABAD' 'WARANGAL'
 'RANGAREDDY' 'ANANTAPUR' 'CHITTOOR' 'KUDDAPAH' 'KURNOOL' 'VELLORE'
 'COIMBATORE' 'DHARMAPURI' 'KANYAKUMARI' 'CHENNAI' 'MADURAI' 'NILGIRIS'
 'RAMANATHAPURA' 'SALEM' 'THANJAVUR' 'TIRUCHIRAPPAL' 'TIRUNELVELI' 'ERODE'
 'PUDUKKOTTAI' 'DINDIGUL' 'VIRUDHUNAGAR' 'SIVAGANGA' 'THOOTHUKUDI'
 'TIRUVANNAMALA' 'NAGAPATTINAM' 'VILUPPURAM' 'CUDDALORE' 'KANCHIPURAM'
 'TIRUVALLUR' 'THENI' 'NAMAKKAL' 'KARUR' 'PERAMBALUR' 'TIRUVARUR'
 'KRISHNAGIRI' 'ARIYALUR' 'TIRUPUR' 'PONDICHERRY' 'KARAIKAL' 'MAHE'
 'YANAM' 'UTTAR KANNADA' 'DAKSHIN KANDA' 'UDUPI' 'BELGAM' 'BIDAR'
 'DHARWAD' 'GULBARGA' 'YADGIR' 'RAICHUR' 'BAGALKOTE' 'GADAG' 'HAVERI'
 'KOPPAL' 'BANGALORE RUR' 'BELLARY' 'CHIKMAGALUR' 'CHITRADURGA' 'KODAGU'
 'HASSAN' 'KOLAR' 'MANDYA' 'MYSORE' 'SHIMOGA' 'TUMKUR' 'BANGALORE URB'
 'CHAMARAJANAGA' 'DAVANGERE' 'RAMNAGAR(BNGR)' 'CHICKBALLAPUR' 'ALAPPUZHA'
 'CANNUR' 'ERNAKULAM' 'KOTTAYAM' 'KOZHIKODE' 'MALAPPURAM' 'PALAKKAD'
 'KOLLAM' 'THRISSUR' 'THIRUVANANTHA' 'IDUKKI' 'KASARGOD' 'PATHANAMTHITTA'
 'WAYANAD' 'LAKSHADWEEP']
Unique States/UTs: NICOBAR, SOUTH ANDAMAN, N & M ANDAMAN, LOHIT, EAST SIANG, SUBANSIRI F.D, TIRAP, ANJAW (LOHIT), LOWER DIBANG, CHANGLANG, PAPUM PARE, LOW SUBANSIRI, UPPER SIANG, WEST SIANG, DIBANG VALLEY, WEST KAMENG, EAST KAMENG, TAWANG(W KAME, KURUNG KUMEY, CACHAR, DARRANG, GOALPARA, KAMRUP, LAKHIMPUR, NORTH CACHAR, NAGAON, SIVASAGAR, BARPETA, DHUBRI, DIBRUGARH, JORHAT, KARIMGANJ, KOKRAJHAR, SHONITPUR, GOLAGHAT, TINSUKIA, HAILAKANDI, DHEMAJI(LAKHI, KARBI ANGLONG, UDALGURI(DARA, KAMRUP METROP, CHIRANG(BONGAI, BAKSA BARPETA, BONGAIGAON, MORIGAON, NALBARI, EAST KHASI HI, JAINTIA HILLS, EAST GARO HIL, RI-BHOI, SOUTH GARO HI, W KHASI HILL, WEST GARO HIL, IMPHAL EAST, SENAPATI, TAMENGLONG, CHANDEL, UKHRUL, THOUBAL, BISHNUPUR, IMPHAL WEST, CHURACHANDPUR, AIZAWL, CHAMPHAI, KOLASIB, LUNGLEI, CHHIMTUIPUI, LAWNGTLAI, MAMIT, SAIHA, SERCHHIP, KOHIMA, TUENSANG, MOKOKCHUNG, DIMAPUR, WOKHA, MON, ZUNHEBOTO, PHEK, KEPHRIE, LONGLENG, PEREN, NORTH TRIPURA, SOUTH TRIPURA, WEST TRIPURA, DHALAI, COOCH BEHAR, DARJEELING, JALPAIGURI, MALDA, SOUTH DINAJPUR, NORTH DINAJPUR, NORTH SIKKIM, EAST SIKKIM, WEST SIKKIM, SOUTH SIKKIM, BANKURA, BIRBHUM, BURDWAN, HOOGHLY, HOWRAH, PURULIA, MURSHIDABAD, NADIA, NORTH 24 PARG, SOUTH 24 PARG, EAST MIDNAPOR, WEST MIDNAPOR, KOLKATA, BALASORE, BOLANGIR, KANDHAMAL/PHU, CUTTACK, DHENKANAL, GANJAM, KALAHANDI, KEONDJHARGARH, KORAPUT, MAYURBHANJ, PURI, SAMBALPUR, SUNDARGARH, BHADRAK, JAJPUR, KENDRAPARA, ANGUL, NAWAPARA, MALKANGIRI, NAWARANGPUR, NAYAGARH, KHURDA, BARGARH, JHARSUGUDA, DEOGARH, RAYAGADA, GAJAPATI, JAGATSINGHAPU, BOUDHGARH, SONEPUR, BOKARO, DHANBAD, DUMKA, HAZARIBAG, PALAMU, RANCHI, SAHIBGANJ, WEST SINGHBHUM, DEOGHAR, GIRIDIH, GODDA, GUMLA, LOHARDAGA, CHATRA, KODERMA, PAKUR, EAST SINGHBHU, GARHWA, SERAIKELA-KHA, JAMTARA, LATEHAR, SIMDEGA, KHUNTI(RANCHI, RAMGARH, BHAGALPUR, EAST CHAMPARAN, DARBHANGA, GAYA, MUNGER, MUZAFFARPUR, WEST CHAMPARAN, PURNEA, GOPALGANJ, MADHUBANI, AURANGABAD, BEGUSARAI, BHOJPUR, NALANDA, PATNA, KATIHAR, KHAGARIA, SARAN, MADHEPURA, NAWADA, ROHTAS, SAMASTIPUR, SITAMARHI, SIWAN, VAISHALI, JAHANABAD, BUXAR, ARARIA, BANKA, BHABUA, JAMUI, KISHANGANJ, SHEIKHPURA, SUPAUL, LAKHISARAI, SHEOHAR, ARWAL, SAHARSA, ALLAHABAD, AZAMGARH, BAHRAICH, BALLIA, BANDA, BARABANKI, BASTI, DEORIA, FAIZABAD, FARRUKHABAD, FATEHPUR, GHAZIPUR, GONDA, GORAKHPUR, HARDOI, JAUNPUR, KANPUR NAGAR, KHERI LAKHIMP, LUCKNOW, MIRZAPUR, PRATAPGARH, RAE BARELI, SITAPUR, SULTANPUR, UNNAO, VARANASI, SONBHADRA, MAHARAJGANJ, MAU, SIDDHARTH NGR, KUSHINAGAR, AMBEDKAR NAGAR, KANNAUJ, BALRAMPUR, KAUSHAMBI, SAHUJI MAHARA, KANPUR DEHAT, CHANDAULI, SANT KABIR NGR, SANT RAVIDAS, SHRAVASTI NGR, AGRA, ALIGARH, BAREILLY, BIJNOR, BADAUN, BULANDSHAHAR, ETAH, ETAWAH, HAMIRPUR, JALAUN, JHANSI, LALITPUR, MAINPURI, MATHURA, MEERUT, MORADABAD, MUZAFFARNAGAR, PILIBHIT, RAMPUR, SAHARANPUR, SHAHJAHANPUR, GHAZIABAD, FIROZABAD, MAHOBA, MAHAMAYA NAGA, AURAIYA, BAGPAT, JYOTIBA PHULE, GAUTAM BUDDHA, KANSHIRAM NAG, ALMORA, CHAMOLI, DEHRADUN, GARHWAL PAURI, NAINITAL, PITHORAGARH, GARHWAL TEHRI, UTTARKASHI, HARIDWAR, CHAMPAWAT, RUDRAPRAYAG, UDHAM SINGH N, BAGESHWAR, AMBALA, GURGAON, HISAR, JIND, KARNAL, MAHENDRAGARH, ROHTAK, BHIWANI, FARIDABAD, KURUKSHETRA, SIRSA, SONEPAT(RTK), YAMUNANAGAR, KAITHAL, PANIPAT, REWARI, FATEHABAD, JHAJJAR, PANCHKULA, MEWAT, PALWAL(FRD), CHANDIGARH, NEW DELHI, CENTRAL DELHI, EAST DELHI, NORTH DELHI, NE DELHI, SW DELHI, NW DELHI, SOUTH DELHI, WEST DELHI, AMRITSAR, BATHINDA, FEROZEPUR, GURDASPUR, HOSHIARPUR, JALANDHAR, KAPURTHALA, LUDHIANA, PATIALA, RUPNAGAR, SANGRUR, FARIDKOT, MOGA, NAWANSHAHR, FATEHGARH SAH, MUKTSAR, MANSA, BARNALA, SAS NAGAR(MGA), TARN TARAN, BILASPUR, CHAMBA, KANGRA, KINNAUR, KULLU, LAHUL & SPITI, MANDI, SHIMLA, SIRMAUR, SOLAN, UNA, ANANTNAG, BARAMULLA, DODA, JAMMU, KATHUA, LADAKH (LEH), UDHAMPUR, BADGAM, KUPWARA, PULWAMA, SRINAGAR, KARGIL, POONCH, RAJOURI, BANDIPORE, GANDERWAL, KULGAM/(ANT), SHOPAN, SAMBA, KISTWAR, REASI, RAMBAN(DDA), BARMER, BIKANER, CHURU, SRI GANGANAGA, JAISALMER, JALORE, JODHPUR, NAGAUR, PALI, HANUMANGARH, AJMER, ALWAR, BANSWARA, BHARATPUR, BHILWARA, BUNDI, CHITTORGARH, DUNGARPUR, JAIPUR, JHALAWAR, JHUNJHUNU, KOTA, SAWAI MADHOPUR, SIKAR, SIROHI, TONK, UDAIPUR, DHOLPUR, BARAN, DAUSA, RAJSAMAND, KARAULI, PRATAPGARH(CHT, BETUL, VIDISHA, BHIND, DATIA, DEWAS, DHAR, GUNA, GWALIOR, HOSHANGABAD, INDORE, JHABUA, MANDSAUR, MORENA, KHANDWA, KHARGONE, RAISEN, RAJGARH, RATLAM, SEHORE, SHAJAPUR, SHIVPURI, UJJAIN, BHOPAL, HARDA, NEEMUCH, SHEOPUR, BARWANI, ASHOKNAGAR(GNA, BURHANPUR, ALIRAJPUR(JBA), BALAGHAT, CHHATARPUR, CHHINDWARA, JABALPUR, MANDLA, NARSINGHPUR, PANNA, REWA, SAGAR, SATNA, SEONI, SHAHDOL, SIDHI, TIKAMGARH, KATNI, DINDORI, UMARIA, DAMOH, ANUPPUR(SHAHD, SINGRAULI, AHMEDABAD, BANASKANTHA, BARODA, BHARUCH, VALSAD, DANGS, KHEDA, MEHSANA, PANCHMAHALS, SABARKANTHA, SURAT, GANDHINAGAR, NARMADA(BRC), NAVSARI(VSD), ANAND(KHR), PATAN(MHSN), DAHOD(PNML), TAPI(SRT), AMRELI, BHAVNAGAR, JAMNAGAR, JUNAGADH, KUTCH, RAJKOT, SURENDRANAGAR, PORBANDAR, DNH, DAMAN, DIU, MUMBAI CITY, RAIGAD, RATNAGIRI, THANE, SINDHUDURG, MUMBAI SUB, NORTH GOA, SOUTH GOA, AHMEDNAGAR, DHULE, JALGAON, KOLHAPUR, NASHIK, PUNE, SANGLI, SATARA, SOLAPUR, NANDURBAR, BEED, NANDED, OSMANABAD, PARBHANI, LATUR, JALNA, HINGOLI, AKOLA, AMRAVATI, BHANDARA, BULDHANA, CHANDRAPUR, NAGPUR, YAVATMAL, WARDHA, GADCHIROLI, WASHIM, GONDIA, BASTAR, DURG, RAIGARH, RAIPUR, SURGUJA, RAJNANDGAON, DANTEWADA, KANKER (NORH, JANJGIR-CHAMP, KORBA, JASHPUR, DHAMTARI, MAHASAMUND, KORIYA, KOWARDHA (KAB, NARAYANPUR, BIJAPUR, EAST GODAVARI, WEST GODAVARI, GUNTUR, KRISHNA, NELLORE, PRAKASAM, SRIKAKULAM, VISAKHAPATNAM, VIZIANAGARAM, ADILABAD, HYDERABAD, KARIMNAGAR, KHAMMAM, MAHABUBNAGAR, MEDAK, NALGONDA, NIZAMABAD, WARANGAL, RANGAREDDY, ANANTAPUR, CHITTOOR, KUDDAPAH, KURNOOL, VELLORE, COIMBATORE, DHARMAPURI, KANYAKUMARI, CHENNAI, MADURAI, NILGIRIS, RAMANATHAPURA, SALEM, THANJAVUR, TIRUCHIRAPPAL, TIRUNELVELI, ERODE, PUDUKKOTTAI, DINDIGUL, VIRUDHUNAGAR, SIVAGANGA, THOOTHUKUDI, TIRUVANNAMALA, NAGAPATTINAM, VILUPPURAM, CUDDALORE, KANCHIPURAM, TIRUVALLUR, THENI, NAMAKKAL, KARUR, PERAMBALUR, TIRUVARUR, KRISHNAGIRI, ARIYALUR, TIRUPUR, PONDICHERRY, KARAIKAL, MAHE, YANAM, UTTAR KANNADA, DAKSHIN KANDA, UDUPI, BELGAM, BIDAR, DHARWAD, GULBARGA, YADGIR, RAICHUR, BAGALKOTE, GADAG, HAVERI, KOPPAL, BANGALORE RUR, BELLARY, CHIKMAGALUR, CHITRADURGA, KODAGU, HASSAN, KOLAR, MANDYA, MYSORE, SHIMOGA, TUMKUR, BANGALORE URB, CHAMARAJANAGA, DAVANGERE, RAMNAGAR(BNGR), CHICKBALLAPUR, ALAPPUZHA, CANNUR, ERNAKULAM, KOTTAYAM, KOZHIKODE, MALAPPURAM, PALAKKAD, KOLLAM, THRISSUR, THIRUVANANTHA, IDUKKI, KASARGOD, PATHANAMTHITTA, WAYANAD, LAKSHADWEEP